language: minimal

branches:
  only:
  - master

script:
  - chmod 555 tools/hugo_0.53_linux # Make tool executable
  - tools/hugo_0.53_linux  # builds website

deploy:  # Deploy to GitHub pages
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  local_dir: public
  on:
    branch: master
