baseURL = "https://rstanleyhum.github.io/www-stanley-hum/"
languageCode = "en-us"
title = "Thoughts on Medicine and Technology"
theme = "minimal"

[params]
    author = "R. stanley Hum"
    description = "The personal website for Stanley Hum."
    githubUsername = "rstanleyhum"
    accent = "red"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["go", "javascript", "python", "scala", "swift"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/post/"
    name = "Posts"
    weight = 2

#[[menu.main]]
#    url = "/project/"
#    name = "Projects"
#    weight = 3

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:r.stanley.hum@gmail.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/rstanleyhum/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/rstanleyhum/"
    name = "twitter"
    weight = 3

[[menu.icon]]
    url = "https://www.linkedin.com/in/rstanleyhum/"
    name = "linkedin"
    weight = 4

[[menu.icon]]
    url = "https://www.stackoverflow.com/story/rstanleyhum/"
    name = "stack-overflow"
    weight = 5

[[menu.icon]]
    url = "https://bitbucket.org/rstanleyhum"
    name = "bitbucket"
    weight = 5