on: 
  push:
    branches:
      - master

name: Build and deploy on push

jobs:
  build:
    name: zbrox/zola-deploy-action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: zbrox/zola-deploy-action
      uses: zbrox/zola-deploy-action@0.12.0
      env:
        TOKEN: ${{ secrets.TOKEN }}
